<?php

namespace App\Consts;

class ParishConsts
{
    //教区の定数
    public const ONE = 1;
    public const TWO = 2;
    public const THREE = 3;
    public const FOUR = 4;
    public const FIVE = 5;
    public const SIX = 6;
    public const SEVEN = 7;
    public const EIGHT = 8;
    public const NINE = 9;
    public const TEN = 10;
    public const ELEVEN = 11;
    public const TWELVE = 12;
    public const THIRTEEN = 13;
    public const FOURTEEN = 14;
    public const FIFTEEN = 15;
    public const SIXTEEN = 16;
    public const SEVENTEEN = 17;
    public const EIGHTEEN = 18;
    public const NINETEEN = 19;
    public const TWENTY = 20;
    public const TWENTY_ONE = 21;
    public const TWENTY_TWO = 22;
    public const TWENTY_THREE = 23;
    public const TWENTY_FOUR = 24;
    public const TWENTY_FIVE = 25;
    public const TWENTY_SIX = 26;
    public const TWENTY_SEVEN = 27;
    public const TWENTY_EIGHT = 28;
    public const TWENTY_NINE = 29;
    public const THIRTY = 30;
    public const THIRTY_ONE = 31;
    public const THIRTY_TWO = 32;
    public const THIRTY_THREE = 33;
    public const THIRTY_FOUR = 34;
    public const THIRTY_FIVE = 35;
    public const THIRTY_SIX = 36;
    public const THIRTY_SEVEN = 37;
    public const THIRTY_EIGHT = 38;
    public const THIRTY_NINE = 39;
    public const FORTY = 40;
    public const FORTY_ONE = 41;
    public const FORTY_TWO = 42;
    public const FORTY_THREE = 43;
    public const FORTY_FOUR = 44;
    public const FORTY_FIVE = 45;
    public const FORTY_SIX = 46;
    public const FORTY_SEVEN = 47;
    public const FORTY_EIGHT = 48;
    public const FORTY_NINE = 49;
    public const FIFTY = 50;
    public const FIFTY_ONE = 51;
    public const FIFTY_TWO = 52;
    public const FIFTY_THREE = 53;
    public const FIFTY_FOUR = 54;
    public const FIFTY_FIVE = 55;
    public const FIFTY_SIX = 56;
    public const FIFTY_SEVEN = 57;
    public const FIFTY_EIGHT = 58;
    public const FIFTY_NINE = 59;
    public const SIXTY = 60;
    public const SIXTY_ONE = 61;
    public const SIXTY_TWO = 62;
    public const SIXTY_THREE = 63;
    public const SIXTY_FOUR = 64;
    public const SIXTY_FIVE = 65;
    public const SIXTY_SIX = 66;
    public const SIXTY_SEVEN = 67;
    public const SIXTY_EIGHT = 68;
    public const SIXTY_NINE = 69;
    public const SEVENTY = 70;
    public const SEVENTY_ONE = 71;
    public const SEVENTY_TWO = 72;
    public const SEVENTY_THREE = 73;
    public const SEVENTY_FOUR = 74;
    public const SEVENTY_FIVE = 75;
    public const SEVENTY_SIX = 76;
    public const SEVENTY_SEVEN = 77;
    public const SEVENTY_EIGHT = 78;
    public const SEVENTY_NINE = 79;
    public const EIGHTY = 80;
    public const EIGHTY_ONE = 81;
    public const EIGHTY_TWO = 82;
    public const EIGHTY_THREE = 83;
    public const EIGHTY_FOUR = 84;
    public const EIGHTY_FIVE = 85;
    public const EIGHTY_SIX = 86;
    public const EIGHTY_SEVEN = 87;
    public const EIGHTY_EIGHT = 88;
    public const EIGHTY_NINE = 89;
    public const NINETY = 90;
    public const NINETY_ONE = 91;
    public const NINETY_TWO = 92;
    public const NINETY_THREE = 93;
    public const NINETY_FOUR = 94;
    public const NINETY_FIVE = 95;
    public const NINETY_SIX = 96;
    public const NINETY_SEVEN = 97;
    public const NINETY_EIGHT = 98;
    public const NINETY_NINE = 99;
    public const ONE_HUNDRED = 100;
    public const PARISH_LIST = [
        '1' => self::ONE,
        '2' => self::TWO,
        '3' => self::THREE,
        '4' => self::FOUR,
        '5' => self::FIVE,
        '6' => self::SIX,
        '7' => self::SEVEN,
        '8' => self::EIGHT,
        '9' => self::NINE,
        '10' => self::TEN,
        '11' => self::ELEVEN,
        '12' => self::TWELVE,
        '13' => self::THIRTEEN,
        '14' => self::FOURTEEN,
        '15' => self::FIFTEEN,
        '16' => self::SIXTEEN,
        '17' => self::SEVENTEEN,
        '18' => self::EIGHTEEN,
        '19' => self::NINETEEN,
        '20' => self::TWELVE,
        '21' => self::TWENTY_ONE,
        '22' => self::TWENTY_TWO,
        '23' => self::TWENTY_THREE,
        '24' => self::TWENTY_FOUR,
        '25' => self::TWENTY_FIVE,
        '26' => self::TWENTY_SIX,
        '27' => self::TWENTY_SEVEN,
        '28' => self::TWENTY_EIGHT,
        '29' => self::TWENTY_NINE,
        '30' => self::THIRTY,
        '31' => self::THIRTY_ONE,
        '32' => self::THIRTY_TWO,
        '33' => self::THIRTY_THREE,
        '34' => self::THIRTY_FOUR,
        '35' => self::THIRTY_FIVE,
        '36' => self::THIRTY_SIX,
        '37' => self::THIRTY_SEVEN,
        '38' => self::THIRTY_EIGHT,
        '39' => self::THIRTY_NINE,
        '40' => self::FORTY,
        '41' => self::FORTY_ONE,
        '42' => self::FORTY_TWO,
        '43' => self::FORTY_THREE,
        '44' => self::FORTY_FOUR,
        '45' => self::FORTY_FIVE,
        '46' => self::FORTY_SIX,
        '47' => self::FORTY_SEVEN,
        '48' => self::FORTY_EIGHT,
        '49' => self::FORTY_NINE,
        '50' => self::FIFTY,
        '51' => self::FIFTY_ONE,
        '52' => self::FIFTY_TWO,
        '53' => self::FIFTY_THREE,
        '54' => self::FIFTY_FOUR,
        '55' => self::FIFTY_FIVE,
        '56' => self::FIFTY_SIX,
        '57' => self::FIFTY_SEVEN,
        '58' => self::FIFTY_EIGHT,
        '59' => self::FIFTY_NINE,
        '60' => self::SIXTY,
        '61' => self::SIXTY_ONE,
        '62' => self::SIXTY_TWO,
        '63' => self::SIXTY_THREE,
        '64' => self::SIXTY_FOUR,
        '65' => self::SIXTY_FIVE,
        '66' => self::SIXTY_SIX,
        '67' => self::SIXTY_SEVEN,
        '68' => self::SIXTY_EIGHT,
        '69' => self::SIXTY_NINE,
        '70' => self::SEVENTY,
        '71' => self::SEVENTY_ONE,
        '72' => self::SEVENTY_TWO,
        '73' => self::SEVENTY_THREE,
        '74' => self::SEVENTY_FOUR,
        '75' => self::SEVENTY_FIVE,
        '76' => self::SEVENTY_SIX,
        '77' => self::SEVENTY_SEVEN,
        '78' => self::SEVENTY_EIGHT,
        '79' => self::SEVENTY_NINE,
        '80' => self::EIGHTY,
        '81' => self::EIGHTY_ONE,
        '82' => self::EIGHTY_TWO,
        '83' => self::EIGHTY_THREE,
        '84' => self::EIGHTY_FOUR,
        '85' => self::EIGHTY_FIVE,
        '86' => self::EIGHTY_SIX,
        '87' => self::EIGHTY_SEVEN,
        '88' => self::EIGHTY_EIGHT,
        '89' => self::EIGHTY_NINE,
        '90' => self::NINETY,
        '91' => self::NINETY_ONE,
        '92' => self::NINETY_TWO,
        '93' => self::NINETY_THREE,
        '94' => self::NINETY_FOUR,
        '95' => self::NINETY_FIVE,
        '96' => self::NINETY_SIX,
        '97' => self::NINETY_SEVEN,
        '98' => self::NINETY_EIGHT,
        '99' => self::NINETY_NINE,
        '100' => self::ONE_HUNDRED,
    ];
}